### ISSUE TITLE
Buscador de persones (todo: recursos)

### ISSUE THREAD

**Issue by guirisan** [guirisan/arrelaires#11]
TEMPS: 1 SETMANA

** APP CORE **

És la ferramenta que permet usar la web en certa manera, aixi que ha de ser intuitiva, senzilla, potent, etc...

- [x] botó per a netejar cada camp per separat (see #40)
- [x] cerca excloent. es mostren els resultats que compleixen tots els requisits del formulari
- [ ] enllaçar camps (see #10)
- [x] select2 a input recursos

#### camps del cercador
- [ ] territoris
select normal, permet un únic valor
restringeix ¿pobles? i ¿comarques? i ¿provincies?
deixar-lo pendent d'activar per a quan es mapege un segon territori
ordenar alfabèticament? 

- [ ] provincies
select normal, permet un únic valor
restringeix ¿pobles? i ¿comarques? i ¿provincies?
deixar-lo desactivat fins que es mapege en altra provincia
ordenar alfabèticament? 

- [ ] comarques
select normal, permet un únic valor
restringeix ¿pobles? i ¿comarques? i ¿provincies?
ordenar alfabèticament? 

- [ ] categories
select normal, permet un únic valor. es mostren les icones (i color?) de les categories
restringeix subcategories
ordenar alfabèticament o d'altra manera? 

- [ ] subcategories
select multiples valors.
ordenar les subcategories dins de categories? (see #22)
ordenar alfabèticament? 

- [ ] recursos
select multiples valors (see #22)
ordenar alfabèticament?

**Comment by guirisan** [comment]
Dubtes:
- A més dels recursos, quins caps han de permetre selecció múltiple?

- [ ] territori
- [ ] comarca
- [ ] poble
- [ ] categoria
- [ ] subcategoria

**Comment by guirisan** [comment]
FALTA: Buscar recursos restrictivament (han de tindre tots els seleccionats)
